name: linter-check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v2
      - name: run-lint
        run: |
          make install
          make lint
